/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_215f78a5 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/bihplitfentxioxyjalb/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  
  if (!url || !key) {
    throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY environment variables');
  }
  
  return createClient(url, key);
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  try {
    const supabase = client()
    const { error } = await supabase.from("kv_store_215f78a5").upsert({
      key,
      value
    });
    if (error) {
      const errorMessage = error.message || JSON.stringify(error) || 'Unknown error';
      
      // Check if this is a Cloudflare/network HTML error or gateway error
      const errorStr = errorMessage.toLowerCase();
      if (errorStr.includes('<!doctype') || errorStr.includes('<html') || 
          errorStr.includes('cloudflare') || errorStr.includes('internal server error') ||
          errorStr.includes('error code 500') || errorStr.includes('gateway error') ||
          errorStr.includes('network connection lost') || errorStr.includes('connection lost')) {
        console.warn(`⚠️ [KV Store] Network/Gateway error setting key "${key}" (transient issue), operation skipped`);
        return; // Silently fail for network errors
      }
      
      console.error(`❌ [KV Store] Error setting key "${key}":`, errorMessage.substring(0, 200));
      throw new Error(`KV Store error setting key "${key}": ${errorMessage.substring(0, 200)}`);
    }
  } catch (error: any) {
    // If error message contains HTML or network error keywords, silently fail
    const errorStr = error?.message?.toLowerCase() || '';
    if (errorStr.includes('<!doctype') || errorStr.includes('<html') || 
        errorStr.includes('cloudflare') || errorStr.includes('internal server error') ||
        errorStr.includes('error code 500') || errorStr.includes('gateway error') ||
        errorStr.includes('network connection lost') || errorStr.includes('connection lost')) {
      console.warn(`⚠️ [KV Store] Network/Gateway error setting key "${key}" (transient issue), operation skipped`);
      return;
    }
    
    console.error(`❌ [KV Store] Unexpected error setting key "${key}":`, error?.message?.substring(0, 200) || error);
    throw error;
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  try {
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_215f78a5").select("value").eq("key", key).maybeSingle();
    if (error) {
      const errorMessage = error.message || JSON.stringify(error) || 'Unknown error';
      
      // Check if this is a Cloudflare/network HTML error or gateway error
      const errorStr = errorMessage.toLowerCase();
      if (errorStr.includes('<!doctype') || errorStr.includes('<html') || 
          errorStr.includes('cloudflare') || errorStr.includes('internal server error') ||
          errorStr.includes('error code 500') || errorStr.includes('gateway error') ||
          errorStr.includes('network connection lost') || errorStr.includes('connection lost')) {
        console.warn(`⚠️ [KV Store] Network/Gateway error for key "${key}" (transient issue), returning null`);
        return null;
      }
      
      console.error(`❌ [KV Store] Error getting key "${key}":`, errorMessage.substring(0, 200));
      throw new Error(`KV Store error for key "${key}": ${errorMessage.substring(0, 200)}`);
    }
    return data?.value;
  } catch (error: any) {
    // If error message contains HTML or network error keywords, return null instead of throwing
    const errorStr = error?.message?.toLowerCase() || '';
    if (errorStr.includes('<!doctype') || errorStr.includes('<html') || 
        errorStr.includes('cloudflare') || errorStr.includes('internal server error') ||
        errorStr.includes('error code 500') || errorStr.includes('gateway error') ||
        errorStr.includes('network connection lost') || errorStr.includes('connection lost')) {
      console.warn(`⚠️ [KV Store] Network/Gateway error for key "${key}" (transient issue), returning null`);
      return null;
    }
    
    console.error(`❌ [KV Store] Unexpected error getting key "${key}":`, error?.message?.substring(0, 200) || error);
    throw error;
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_215f78a5").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_215f78a5").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  try {
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_215f78a5").select("value").in("key", keys);
    if (error) {
      const errorMessage = error.message || JSON.stringify(error) || 'Unknown error';
      
      // Check if this is a Cloudflare/network HTML error or gateway error
      const errorStr = errorMessage.toLowerCase();
      if (errorStr.includes('<!doctype') || errorStr.includes('<html') || 
          errorStr.includes('cloudflare') || errorStr.includes('internal server error') ||
          errorStr.includes('error code 500') || errorStr.includes('gateway error') ||
          errorStr.includes('network connection lost') || errorStr.includes('connection lost')) {
        console.warn(`⚠️ [KV Store] Network/Gateway error getting multiple keys (transient issue), returning empty array`);
        return [];
      }
      
      console.error(`❌ [KV Store] Error getting multiple keys:`, errorMessage.substring(0, 200));
      throw new Error(errorMessage.substring(0, 200));
    }
    return data?.map((d) => d.value) ?? [];
  } catch (error: any) {
    // If error message contains HTML or network error keywords, return empty array
    const errorStr = error?.message?.toLowerCase() || '';
    if (errorStr.includes('<!doctype') || errorStr.includes('<html') || 
        errorStr.includes('cloudflare') || errorStr.includes('internal server error') ||
        errorStr.includes('error code 500') || errorStr.includes('gateway error') ||
        errorStr.includes('network connection lost') || errorStr.includes('connection lost')) {
      console.warn(`⚠️ [KV Store] Network/Gateway error getting multiple keys (transient issue), returning empty array`);
      return [];
    }
    
    console.error(`❌ [KV Store] Unexpected error getting multiple keys:`, error?.message?.substring(0, 200) || error);
    throw error;
  }
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_215f78a5").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  try {
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_215f78a5").select("key, value").like("key", prefix + "%");
    if (error) {
      const errorMessage = error.message || JSON.stringify(error) || 'Unknown error';
      
      // Check if this is a Cloudflare/network HTML error or gateway error
      const errorStr = errorMessage.toLowerCase();
      if (errorStr.includes('<!doctype') || errorStr.includes('<html') || 
          errorStr.includes('cloudflare') || errorStr.includes('internal server error') ||
          errorStr.includes('error code 500') || errorStr.includes('gateway error') ||
          errorStr.includes('network connection lost') || errorStr.includes('connection lost')) {
        console.warn(`⚠️ [KV Store] Network/Gateway error for prefix "${prefix}" (transient issue), returning empty array`);
        return [];
      }
      
      console.error(`❌ [KV Store] Error getting by prefix "${prefix}":`, errorMessage.substring(0, 200));
      throw new Error(errorMessage.substring(0, 200));
    }
    // 🔥 FIX: Return { key, value } objects, not just values
    return data ?? [];
  } catch (error: any) {
    // If error message contains HTML or network error keywords, return empty array
    const errorStr = error?.message?.toLowerCase() || '';
    if (errorStr.includes('<!doctype') || errorStr.includes('<html') || 
        errorStr.includes('cloudflare') || errorStr.includes('internal server error') ||
        errorStr.includes('error code 500') || errorStr.includes('gateway error') ||
        errorStr.includes('network connection lost') || errorStr.includes('connection lost')) {
      console.warn(`⚠️ [KV Store] Network/Gateway error for prefix "${prefix}" (transient issue), returning empty array`);
      return [];
    }
    
    console.error(`❌ [KV Store] Unexpected error getting by prefix "${prefix}":`, error?.message?.substring(0, 200) || error);
    throw error;
  }
};